name: jellyfin_media_management_tool
description: "A powerful cross-platform desktop tool for organizing and managing media files according to Jellyfin naming standards."
publish_to: 'none'

version: 0.9.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  path: ^1.9.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  media_kit: ^1.1.10
  media_kit_libs_video: ^1.0.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
